spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/h10SMiTwih
    driverClassName: com.mysql.jdbc.Driver
    username: h10SMiTwih
    password: 8ivcvCL0wH
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
hibernate:
  hbm2ddl:
    auto: create-drop